trigger:
  - dev
  - test
  - uat

resources:
  - repo: self
pool:
  name: agent-build

variables:
  tag: "$(Build.BuildId)"
  # Agent Pool Self-host
  MyAgentPool: "agent-build"
  
stages:
  - stage: Build
    displayName: "Build Artifacts Stage"
    jobs:
      - job: Build
        displayName: Build Artifacts
        pool: $(MyAgentPool)
        steps:
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(Build.Repository.LocalPath)"
              includeRootFolder: true
              archiveType: "zip"
              archiveFile: "$(Build.Repository.LocalPath)/$(Build.BuildId).zip"
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.Repository.LocalPath)/$(Build.BuildId).zip"
              ArtifactName: "drop"
              publishLocation: "Container"