apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{Build.BuildBranch}#-deployment
  labels:
    app: #{Build.BuildBranch}#
  namespace: #{Build.NameSpace}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{Build.BuildBranch}#
  template:
    metadata:
      labels:
        app: #{Build.BuildBranch}#
    spec:
      containers:
        - name: #{Build.AppName}#
          image: #{Build.BuildURLImage}#:#{Build.BuildId}#
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: #{Build.BuildBranch}#-configmap
            # - secretRef:
            #     name: alitaa-backend-gpt-secret
          resources:
            requests:
              cpu: 300m