# Autoscaling more than 60% CPU
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alitaa-cpu-autoscaling
  namespace: alitaa-aks-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alitaa-aks-ns
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
