# Autoscaling more than 60% CPU
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: #{Build.BuildBranch}#-cpu-autoscaling
  namespace: #{Build.NameSpace}#
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: #{Build.BuildBranch}#-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
